### ISSUE TITLE
VS Code extension crashing server

### ISSUE THREAD

**Issue by Stanzilla** [web-infra-dev/oxc#1131]
Installed the VSC extension today, on a WSL2 instance on Windows, it's crashing with the following:

```
/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/target/release/oxc_vscode: 1: Syntax error: word unexpected (expecting ")")
[Error - 8:45:11 AM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 8:45:11 AM] oxc client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 8:45:11 AM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 8:45:11 AM] Connection to server got closed. Server will restart.
true
/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/target/release/oxc_vscode: 1: Syntax error: word unexpected (expecting ")")
[Error - 8:45:11 AM] Client oxc: connection to server is erroring. Shutting down server.
[Error - 8:45:11 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Gl.shutdown (/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/out/main.js:39:8639)
	at Gl.stop (/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/out/main.js:39:8218)
	at Gl.stop (/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/out/main.js:39:51864)
	at Gl.handleConnectionError (/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/out/main.js:39:14011)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 8:45:11 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 8:45:11 AM] oxc client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 8:45:11 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 8:45:11 AM] The oxc server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
/home/stan/.vscode-server/extensions/oxc.oxc-vscode-0.0.1/target/release/oxc_vscode: 1: Syntax error: word unexpected (expecting ")")
```

**Comment by sairion** [comment]
it seems only mac build is available for 0.0.1 https://twitter.com/boshen_c/status/1719615318463803746

**Comment by Boshen** [comment]
If anyone is interested in helping out: https://github.com/web-infra-dev/oxc/issues/1127

**Comment by Boshen** [comment]
I published v0.0.3 which should support all 6 platforms listed below

<img width="579" alt="image" src="https://github.com/web-infra-dev/oxc/assets/1430279/3ef6e952-e47c-4dc1-931b-a1a1a60355ab">

**Comment by Stanzilla** [comment]
Awesome, will test!

**Comment by Boshen** [comment]
It is confirmed by a contributor that seems works on windows now.
